# Generated by Django 4.2.4 on 2023-12-31 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("meetups", "0004_participant_meetup_participants"),
    ]

    operations = [
        migrations.AddField(
            model_name="meetup",
            name="date",
            field=models.DateField(default="2024-04-04"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="meetup",
            name="organizer_email",
            field=models.EmailField(default="test@tu.com", max_length=254),
            preserve_default=False,
        ),
    ]
