# Generated by Django 4.2.4 on 2024-01-12 15:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_post_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="post_time",
            field=models.TimeField(default=datetime.time(23, 14, 53, 113492)),
        ),
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="post-image/"),
        ),
    ]
