# Generated by Django 4.2.4 on 2024-01-18 12:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0004_post_post_time_alter_post_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post_time",
            field=models.DateTimeField(
                default=datetime.datetime(2024, 1, 18, 20, 41, 16, 924083)
            ),
        ),
    ]
