# Generated by Django 4.2.4 on 2024-01-19 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0005_alter_post_post_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post_time",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
