# Generated by Django 4.2.4 on 2024-01-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0007_post_classification_post_watchpeoplecount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="watchpeoplecount",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
