# Generated by Django 4.2.4 on 2024-01-23 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0008_alter_post_watchpeoplecount"),
    ]

    operations = [
        migrations.CreateModel(
            name="IpAddress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ip", models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name="post",
            name="viewersip",
            field=models.ManyToManyField(blank=True, to="posts.ipaddress"),
        ),
    ]
