# Generated by Django 4.2.4 on 2024-01-23 13:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0009_ipaddress_post_viewersip"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="watchpeoplecount",
        ),
    ]
