# Generated by Django 4.2.4 on 2024-01-24 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0010_remove_post_watchpeoplecount"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="posterip",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posterip",
                to="posts.ipaddress",
            ),
        ),
        migrations.AlterField(
            model_name="ipaddress",
            name="ip",
            field=models.GenericIPAddressField(unique=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="viewersip",
            field=models.ManyToManyField(
                blank=True, related_name="viewersip", to="posts.ipaddress"
            ),
        ),
    ]
